### ISSUE TITLE
Executing when .net full is already installed

### ISSUE THREAD

**Issue by jvivona** [KoenZomers/pfSenseBackup#11]
With 2.5.x - if I attempt to run backups without the -o parameter & the .net FULL is already installed on the server - we are getting backups saved to the .net full path on the C drive instead of the "current" directory.   When I run the source in debug mode - I can see where it's getting the path from, but it seems like in certain scenarios it's being loaded into a temp space & then when the current path is being requested from Assembly.GetExecutingAssembly().Location, the path is in correct.

I know the workaround is to specify -o, but any thoughts on a more general fix?

**Comment by KoenZomers** [comment]
Interesting one. Sure know where this one is coming from. I've packaged the .NET Core file as a single file package to avoid it being a messy stack of files. This means on run it will extract itself to a temporary location. That must be what it's using. I'll fix it.

**Comment by jvivona** [comment]
Gotcha.  so not a .net core vs full, it's a "unzip" type operation.    I know full .net - but I'm just starting to dabble in core.   Thanks!

**Comment by KoenZomers** [comment]
Resolved in https://github.com/KoenZomers/pfSenseBackup/releases/tag/2.5.2

Believe me, once you get the hang of .NET Core, you never want to go back anymore to .NET Framework :)
