### ISSUE TITLE
pfsense 2.5.0 encrypted backup requests the password confirmation

### ISSUE THREAD

**Issue by msim888** [KoenZomers/pfSenseBackup#14]
**Describe the bug**
pfsense 2.5.0 encrypted backup requests the password confirmation so the -e option doesn't work anymore

**To Reproduce**
Use -e option

**Comment by KoenZomers** [comment]
Thanks for reporting @msim888. This has been resolved in [version 2.6.0](https://github.com/KoenZomers/pfSenseBackup/releases/tag/2.6.0) of the pfSenseBackup tool.

**Comment by msim888** [comment]
Thank you very much, Koen!
Great job!
