### ISSUE TITLE
 Error: The SSL connection could not be established, see inner exception. 

### ISSUE THREAD

**Issue by mrventerj** [KoenZomers/pfSenseBackup#16]
Hi

I am running the script succesfully on multiple pfsense routers for backups.

I added a new router but I get this error on it when running the batch:

Connecting using protocol version 2.5.0
Error: The SSL connection could not be established, see inner exception. The handshake failed due to an unexpected packet format.

Do you know what might cause this?

Syntax:
F:
cd F:\Backups\RouterBackups
pfSenseBackupv2.exe -u backup -p xxxxxxx -s x.x.x.x -o f:\Backups\RouterBackups\RouternameFolderx

**Comment by mrventerj** [comment]
@KoenZomers Hi Koen, any idea what could be the issue with the error?

**Comment by KoenZomers** [comment]
Hi @mrventerj , try adding -usessl to the cmdline parameters and see if that resolves it for you

**Comment by mrventerj** [comment]
@KoenZomers Thx Koen, that worked for me, I add the -uselessl at the end instead of using it before the directory, which I didn't try before.

**Comment by KoenZomers** [comment]
Glad to see it worked. Thanks for circling this back!
