### ISSUE TITLE
[BUG] Looks like it not work for pfSense Plus 22.05

### ISSUE THREAD

**Issue by michaelmsonne** [KoenZomers/pfSenseBackup#17]
**Describe the bug**
Looks like it not work on pfSense Plus 22.05 from [Confirmation] works with pfSense Plus 21.02 #15

**To Reproduce**
Backup via etc.: .\pfsenseBackup.exe -u xxxxxxxxxxxxxx -p xxxxxxxxxxxxxxxx -s pfsense.home.local  -o C:\Temp
And you get this:
Connecting using protocol version 2.5.0
Authenticating
Requesting backup file
Retrieving backup file
No valid backup contents returned

**Expected behavior**
A downloaded backup of the configuration

**N.B:** Looks like it not shows invalid username/password too, id you change it to a wrong username or password.
Shows:
Authenticating
Requesting backup file
....

**Versions (please complete the following information):**
- OS: Windows 11
- pfSense: 22.05-RELEASE
- pfSenseBackup: v2.6.0

**Comment by jvivona** [comment]
I am running 22.05 with backup 2.6.0  and I'm not having any issues currently.  
![image](https://user-images.githubusercontent.com/1454249/211164084-dca13764-cdbb-4836-b740-5f38593f07bc.png)
![image](https://user-images.githubusercontent.com/1454249/211164090-086699f5-77b2-4b5b-bc01-de665762e9d8.png)

**Comment by jvivona** [comment]
have you checked logging into the web interface using the user/password you have & make sure you have access to Diagnostics -> Backup/Restore and can get to this screen & manually run a backup?
![image](https://user-images.githubusercontent.com/1454249/211164196-95e1d847-4bf4-46da-a34e-24ae04fdba9f.png)

**Comment by michaelmsonne** [comment]
> I am running 22.05 with backup 2.6.0 and I'm not having any issues currently. ![image](https://user-images.githubusercontent.com/1454249/211164084-dca13764-cdbb-4836-b740-5f38593f07bc.png) ![image](https://user-images.githubusercontent.com/1454249/211164090-086699f5-77b2-4b5b-bc01-de665762e9d8.png)

Hmm strange - when i login with my "automation-read" user i see this fine:
![gui](https://user-images.githubusercontent.com/49366751/211164342-7eed6549-9ad3-41fb-8455-162b1382602c.png)

But i get this error:
![error](https://user-images.githubusercontent.com/49366751/211164341-4b0c6da7-2286-4948-bafd-0da1480b6491.png)

**Comment by jvivona** [comment]
what happens if from the web interface you hit "download configuration" with that user - do you get a valid backup XML?

and have you tried without the -o option?

**Comment by michaelmsonne** [comment]
If i download backup from web interface with the "automation-read" user i get this fine:
![from gui with automation user](https://user-images.githubusercontent.com/49366751/211165017-e8b9a7ec-9108-44e2-bb6b-3e37273a0e07.png)

If I look into the .xml file it looks fine too and have 4661 lines of code.

If i not set the -o option i get the same error... 🤔

**Comment by jvivona** [comment]
I'm going to let @KoenZomers chime in - I don't have a computer with me which I can pull the source and look at it.  I can't remember if there's a "verbose" command that gives more logging details.   I can peek at it prob tomorrow AM.

**Comment by michaelmsonne** [comment]
There is not a "verbose" command as i can see..

Lets see if @KoenZomers have som inputs - thanks for your help for now @jvivona! ❤️

**Comment by michaelmsonne** [comment]
My bad - see now I missed the -usessl argument at i use https 😂

**Comment by michaelmsonne** [comment]
My bad - see now I missed the -usessl argument at i use https 😂
