### ISSUE TITLE
[FEATURE REQUEST] Include extra data

### ISSUE THREAD

**Issue by kingwilliam** [KoenZomers/pfSenseBackup#18]
**Is your feature request related to a problem? Please describe.**
if "Include extra data" function is more better.

**Describe the solution you'd like**
add function to backup "extra data"

**Describe alternatives you've considered**
no alternatives solution

**Additional context**
![pf](https://github.com/KoenZomers/pfSenseBackup/assets/3607762/7b909a0a-3439-456c-9cd2-db4e4ccc4e43)

**Comment by KoenZomers** [comment]
Added in [version 2.7.0](https://github.com/KoenZomers/pfSenseBackup/releases/tag/2.7.0). By default it will include the extra data in this version. You don't need to specify anything additional for this. If you _don't_ want the additional data, you can specify `-noextradata`.
