### ISSUE TITLE
TLS 1.2 Issue

### ISSUE THREAD

**Issue by ymolinet** [KoenZomers/pfSenseBackup#3]
First, great job, You safe a lot of my time.
Randomly, you can receive an exception caught by the SSL Certificat validation.
To fix it, just add 

```
ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls |
                                       SecurityProtocolType.Tls11 |
                                       SecurityProtocolType.Tls12;
```

**Comment by KoenZomers** [comment]
Thanks for your advice @ymolinet! I've just released v2.4.3 in which these protocols have been enabled.
