### ISSUE TITLE
Unsupported pfsesen version provided 2.3.4

### ISSUE THREAD

**Issue by clint1337** [KoenZomers/pfSenseBackup#4]
Hi,

Ive got the latest pfsense version, then i noticed this program.
Any chance it will be supported ?

**Comment by KoenZomers** [comment]
Hi there. It should work with the latest version. Are you running into trouble using it against the latest version?

**Comment by clint1337** [comment]
I just started with it, dont know if its because of the version or because i failed somewhere.
when i remove "-v 2.3.4"
i get 
"Error: The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel."

**Comment by clint1337** [comment]
Oh i forgot the -usessl.

:D
