### ISSUE TITLE
Error 400 Bad request 

### ISSUE THREAD

**Issue by randysrs** [KoenZomers/pfSenseBackup#7]
not sure what the issue is .  
i have 7 FW working fine but this one just isnt happy .  

connecting using protocol 2.3.3
error the remote server returned an error 400 bad request . 

i am sure it is something i goofed up .  PFsenseBackup rocks 

![image](https://user-images.githubusercontent.com/58384233/73132097-48c4f600-3fcb-11ea-8347-016405f6ab3d.png)

**Comment by randysrs** [comment]
think you can close this .  system required SSL . worked after that

**Comment by KoenZomers** [comment]
Glad you're liking it. Was about to comment with the usessl flag. 99% of the inquiries I get are typically caused by having forgotten that flag :)
