### ISSUE TITLE
How do I encrypt backups?

### ISSUE THREAD

**Issue by lhanson** [KoenZomers/pfSenseBackup#8]
It would be helpful if the README included information on what encryption algorithm is used to encrypt the backups, and how to decrypt them.

**Comment by KoenZomers** [comment]
It's using the encryption built into pfSense. The tool itself doesn't perform any kind of encryption on it. Here's a link I've found with more information on the encryption used and how to manually decrypt pfSense backups:

https://forum.netgate.com/topic/139561/pfsense-xml-config-file-can-we-decrypt-it-manually/3

**Comment by lhanson** [comment]
That makes sense, thanks. Given that, I presume that the tool is using the login password as the encryption password as well? Maybe a line in the docs to clarify this would help others in the future?

**Comment by KoenZomers** [comment]
With the -e argument to indicate that you want to have pfSense encrypt the backup, you can provide a password as shown in this sample:

https://github.com/KoenZomers/pfSenseBackup/blob/67c6f045df6083caece272b7acb69bf410c4f1ae/pfSenseBackup/Program.cs#L319

**Comment by lhanson** [comment]
Argh, that's painfully obvious, sorry for the noise and thanks for the help!
